name: Sync Files to Repo B

on:
  push:
    branches:
      - main  # Runs when changes are pushed to Repo A's main branch
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Clone Repo B
        run: |
          git clone https://github.com/singhrakeshy/Repo-B.git
          cd Repo-B
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Copy All Files to Repo B
        run: |
          rsync -av --exclude='.git' . Repo-B/  # Copy all files except .git folder
          cd Repo-B
          git add .
          git commit -m "Sync changes from Repo A" || echo "No changes to commit"
          git push origin main
